### ISSUE TITLE
Creating voucher table: Checking Altitude box lead to Error 500 since this field no longer exists

### ISSUE THREAD

**Issue by mariespe** [VoSeq/VoSeq#390]
Hi Carlos,

Checking the altitude box when creating a voucher table leads to an Error 500 since this field doesn't exist any more in Voseq, but has been replaced by two fields: Minimum altitude and Maximum altitude. Would it be possible to replace Altitude with Minimum altitude and Maximum altitude? At the moment it's not possible to output any altitude data when creating a voucher table.

Marianne

**Comment by carlosp420** [comment]
fixed with #395 

A generated dataset with selected max and min altitudes will be similar to :
<img width="479" alt="Screen Shot 2020-06-27 at 00 36 31" src="https://user-images.githubusercontent.com/710117/85915798-4d0e6d00-b810-11ea-8d8c-214c44870a7a.png">

Note that this version of VoSeq has different folder structure. It should work out of the box though. It can be used as native installation or you can installing it using Docker (see readme file for more details). Support for vagrant has been dropped.
